### ISSUE TITLE
Benchmark mount and use for snapshots

### ISSUE THREAD

**Issue by gavinorland** [stevesims/govuk-frederic#17]
We're advised not to use `mount` for, performance reasons, and almost everything can be done without it - even tests on whether style rules are applied by styled components. But unless `mount` is used, the styles are not output into a snapshot with [`jest-emotion`](https://emotion.sh/docs/testing).

If overhead of using `mount` proves to be insignificant then we should perform at least one later render using it and snapshot that, as an additional layer of security in case someone changes style rules in a component.

Rules that are applied conditionally should continue to be tested using `jest-emotion`'s `toHaveStyleRule`.

**Comment by Loque-** [comment]
I reckon we should just to do it : D was hoping someone else had already created a performance test but couldn't find one with my swift google search : )

**Comment by gavinorland** [comment]
Ok, I'm sold! We can implement this one and I will raise an issue to retrofit the others when we have a chance.

**Comment by gavinorland** [comment]
Yes, okay - we'll amend existing tests to include this as soon as we have time. ☺

**Comment by gavinorland** [comment]
Plot thickens as I just noticed `shallow` _does_ render the style rules into the snapshot - those of the base component only, of course :) But of course we often use constituent SCs too! So where we want the whole lot we should use `mount`.

**Comment by gavinorland** [comment]
Let's just retrofit these as and when we are dealing with the components or making new ones.
