### ISSUE TITLE
Remove unused dependencies

### ISSUE THREAD

**Issue by Loque-** [stevesims/govuk-frederic#25]

**Comment by gavinorland** [comment]
@Loque- noted `react-motion`. It looks like there are others, too, unless I'm mistaken: `react-markdown`, `storybook-readme`...

**Comment by gavinorland** [comment]
Notes to self...

- `react-collapse` is needed by `table-accordion-group`
- `react-motion` is needed by `react-collapse`
- `react-motion` is also needed by Storybook
- `sinon` can be removed now using different testing
- `react-test-renderer` - ditto
- `storybook-readme` can be moved into the Storybook folder's own `package.json`

**Comment by gavinorland** [comment]
@taranchauhan, I have pushed [a branch](https://github.com/stevesims/govuk-frederic/tree/feature/remove-unused-deps) for this. I wonder if you would have a chance to pick this issue up though, the reason being that I am restricted to 3G here and I really want to be able to wipe `node_modules` and reinstall to test whether everything still works - but installing those is a 500MB download.

It looks to me like there _are_ some deps that don't need to be in the root `package.json` but could be in sub-`package.json`s, like Storybook's or individual components. It's going to need more looking at though...

**Comment by gavinorland** [comment]
Resolved by https://github.com/stevesims/govuk-frederic/pull/41
