### ISSUE TITLE
Odd CounterBar interaction with react-router Link

### ISSUE THREAD

**Issue by stevesims** [stevesims/govuk-frederic#39]
When using a `Link` component from `react-router` with either of the `CounterBar` item components we get an odd complaint in the JS console saying:
```
Warning: Received `true` for a non-boolean attribute `active`
```

We should consider doing two things to address this:
1) stripping props we're using before passing them through
2) using `selected` as the name for this prop, as that's it's real purpose

**Comment by gavinorland** [comment]
This the same as what I saw with `empty` then, and is happening I think because `active` is sometimes `undefined`, not strictly `true` or `false`. The same fix works for it in `Wrapper` props:

`active={active ? 1 : 0}`

**Comment by gavinorland** [comment]
Fixed by https://github.com/stevesims/govuk-frederic/pull/42
