### ISSUE TITLE
Add and use govuk-react's withWhitespace HOC

### ISSUE THREAD

**Issue by stevesims** [stevesims/govuk-frederic#44]
Many/most components within govuk-frederic should use `withWhitespace` - for example the `Table` component should automatically get whitespace below it

**Comment by gavinorland** [comment]
What's the preferred `marginBottom` to be sent in? For example:

`export default withWhiteSpace({ marginBottom: 3 })(Table);`

If you have a list of those that should have white space and any variance between them I'll be happy to add this.

**Comment by stevesims** [comment]
to be honest, i don't know what the preferred value should be - for reference check to see what's typically used in govuk-react.

As for which components should get whitespace - it looks to me like `Table`, `CompactTableAccordionGroup`, `TableAccordionGroup`, `CounterBar` and `Keyline`

**Comment by gavinorland** [comment]
Right, I'll assign this to myself and compare with govuk-react... :thumbsup:

**Comment by gavinorland** [comment]
This is addressed by https://github.com/stevesims/govuk-frederic/pull/48 but there is not always an equivalent component in govuk-react - just let me know if margins should be different when you see these components in the sec-env.

**Comment by gavinorland** [comment]
Resolved by https://github.com/stevesims/govuk-frederic/pull/48
