### ISSUE TITLE
Ensure that props are spread onto all the components

### ISSUE THREAD

**Issue by taranchauhan** [stevesims/govuk-frederic#49]
Ensure that all props are spread on all the components like so...

```jsx
const LeadParagraph = props => <StyledParagraph {...props} />;
```

This is so we automatically allow props such as className and mb for example to be passed down to the component as attributes.

**Comment by gavinorland** [comment]
Closing this following https://github.com/stevesims/govuk-frederic/pull/51, however https://github.com/stevesims/govuk-frederic/issues/56 has been opened for consideration.
