### ISSUE TITLE
Table has some funky formatting

### ISSUE THREAD

**Issue by stevesims** [stevesims/govuk-frederic#7]
TD elements in Table get padding for the first and last elements in a row, but not the others.  TD styling should be more consistent - this probably means adding `padding: 15px` to the base TD styling.

It could also be good to be able to specify cell alignment.  Currently all TD elements have `vertical-align: baseline` set which makes table rows that include a tall element (such as an image) look funky.  It would be nice to support optionally setting the align to `top`.

**Comment by gavinorland** [comment]
Thanks Steve - I'll look into this.

**Comment by gavinorland** [comment]
How about using `padding: '15px 8px'` for both `th`s and `td`s, and removing the pseudo-selectors? This looks good in the Storybook but I could certainly just do `padding: '15px'` instead.

**Comment by gavinorland** [comment]
Right... In `govuk/react` both both first _and_ middle cells have right padding, but no left padding, and its set in `em`s:

`'0.63158em 1.05263em 0.47368em 0'`

The `last-child` is set so this cell has no left or right padding.

In Frederic here, middle cells have no right or left padding. Two options, I think:
- Add the same padding to all cells and give the table a negative margin of `-8px`. This as I recall is how Bootstrap use to handle this.
- Add padding to all cells and override either end with the pseudos.

An pref on this one? Also as to whether to use px or ems across both repos!
