### ISSUE TITLE
rowsFromObject in utils should not default to an empty string

### ISSUE THREAD

**Issue by stevesims** [stevesims/govuk-frederic#87]
On the following line:
https://github.com/stevesims/govuk-frederic/blob/8bd56933a3503d5b9c69521842d004265aea6e69/packages/utils/src/tableUtils/index.js#L38

we should not default `result` here to an empty string.  Doing so prevents the behaviour on the following line of detecting whether a transformed value has been returned as `null` and if so skipping the inclusion of that row from operating

**Comment by Loque-** [comment]
Fixed in https://github.com/stevesims/govuk-frederic/pull/88
