### ISSUE TITLE
Table needs better solutions for naming fields

### ISSUE THREAD

**Issue by stevesims** [stevesims/govuk-frederic#9]
Our `Table` component supports naming fields, however the current code for applying names effectively supports only a single name per column.  A common use-case for `Table` however is to have a 2-column table with a heading column and a value column.

We should provide a way of supporting this use-case.

**Comment by stevesims** [comment]
Perhaps this could be handled by making `names` slots optionally contain an array, where the index into that array is the row being displayed.

Needs more thought tho

**Comment by gavinorland** [comment]
Yes, this changes it a fair bit, doesn't it, because also the layout also becomes headings down the first column instead of across the first row. A prop might need passing telling the table which kind of layout it's going to be unless it can inferred from the data sent to it...
